# Generated by Django 5.0.2 on 2024-08-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_orderitem_price_remove_order_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='food_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
