# Generated by Django 5.0.2 on 2024-08-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='name',
        ),
    ]
