# Generated by Django 5.0.2 on 2024-08-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_item_orderitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
