# Generated by Django 6.0.3 on 2026-04-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_order_items_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
